inquirybuilder/force-app/main/default/objects/CSA_Element_Web_Resource__c/CSA_Element_Web_Resource__c.object-meta.xml
<CustomObject>
    <label>Element Web Resource</label>
    <nameField>
        <displayFormat>EWR-{0000}</displayFormat>
        <label>Element Web Resource Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Element Web Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

inquirybuilder/force-app/main/default/objects/CSA_Element_Web_Resource__c/fields/Inquiry_Element__c.field-meta.xml
<CustomField>
    <fullName>Inquiry_Element__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inquiry Element</label>
    <referenceTo>CSA_Inquiry_Element_Definition__c</referenceTo>
    <relationshipLabel>Element Web Resources</relationshipLabel>
    <relationshipName>Element_Web_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

inquirybuilder/force-app/main/default/objects/CSA_Element_Web_Resource__c/fields/Web_Resource__c.field-meta.xml
<CustomField>
    <fullName>Web_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Web Resource</label>
    <referenceTo>CSA_Web_Resources__c</referenceTo>
    <relationshipLabel>Element Web Resources</relationshipLabel>
    <relationshipName>Element_Web_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

inquirybuilder/force-app/main/default/objects/CSA_Inquiry_Template__c/CSA_Inquiry_Template__c.object-meta.xml
<CustomObject>
    <label>Inquiry Template</label>
    <nameField>
        <label>Inquiry Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inquiry Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

inquirybuilder/force-app/main/default/objects/CSA_Web_Resources__c/CSA_Web_Resources__c.object-meta.xml
<CustomObject>
    <label>Web Resource</label>
    <nameField>
        <displayFormat>WR-{0000}</displayFormat>
        <label>Web Resources Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Web Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

inquirybuilder/force-app/main - final/default/objects/CSA_Web_Resources__c/fields/Resource_Name__c.field-meta.xml
<CustomField>
    <fullName>Resource_Name__c</fullName>
    <label>Resource Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

inquirybuilder/force-app/main - final/default/objects/CSA_Web_Resources__c/fields/Resource_Url__c.field-meta.xml
<CustomField>
    <fullName>Resource_Url__c</fullName>
    <label>Resource Url</label>
    <type>Url</type>
</CustomField>

inquirybuilder/force-app/main/default/classes/InquiryBuilderGetRecords.cls
public with sharing class InquiryBuilderGetRecords {

    @AuraEnabled
    public static List<CSA_Inquiry_Template__c> getCategory() {

        try {
            
        List<CSA_Inquiry_Template__c> category = [SELECT Id,Category_Name__c,Help_Text__c
                                                   FROM CSA_Inquiry_Template__c];

        return category;

        } 
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

    }

    @AuraEnabled
    public static List<CSA_Element_Web_Resource__c> getWebResource(string elementId){
        try {

            List<CSA_Element_Web_Resource__c> resources = [SELECT Id,Name,Inquiry_Element__c,Web_Resource__r.Resource_Url__c,Web_Resource__r.Resource_Name__c 
                                                            FROM CSA_Element_Web_Resource__c 
                                                            WHERE Inquiry_Element__c =:elementId];
            
            System.debug('print');
            return resources;

            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}